site_name: 'test-app'

nav:
  - Home: index.md
  # - Introduction: introduction.md
  # - Install: install.md
  # - Configuration: configuration.md
  # - Example: example.md
  # - Development: development.md
  # - Deployment: deployment.md
  # - Release notes: release_notes.md

plugins:
  - techdocs-core