site_name: 'test-app'

nav:
  - Home: 'docs/index.md'
  - Introduction: 'docs/introduction.md'
  - Install: 'docs/install.md'
  - Configuration: 'docs/configuration.md'
  - Example: 'docs/example.md'
  - Development: 'docs/development.md'
  - Deployment: 'docs/deployment.md'
  - Release notes: 'docs/release_notes.md'

plugins:
  - techdocs-core